# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_0/design_1_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_0 || ORIG_REF_NAME==design_1_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_1_0/design_1_util_vector_logic_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_1_0 || ORIG_REF_NAME==design_1_util_vector_logic_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_2/design_1_util_vector_logic_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_2 || ORIG_REF_NAME==design_1_util_vector_logic_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_4/design_1_util_vector_logic_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_4 || ORIG_REF_NAME==design_1_util_vector_logic_0_4} -quiet] -quiet

# XDC: c:/Users/brebu/OneDrive/Desktop/LaburiCN/Lab1/Lab1.gen/sources_1/bd/design_1/design_1_ooc.xdc
